# Generated by Django 2.1.1 on 2018-09-14 06:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='river',
            old_name='leauge',
            new_name='relatedLeague',
        ),
    ]
