# Generated by Django 2.1.1 on 2018-09-14 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0002_auto_20180914_0026'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='basePoints',
            field=models.IntegerField(null=True),
        ),
    ]
