# Generated by Django 2.1.1 on 2018-09-14 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0003_fish_basepoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='river',
        ),
        migrations.AddField(
            model_name='fish',
            name='river',
            field=models.ManyToManyField(related_name='river', to='flyFishing.River'),
        ),
    ]
