# Generated by Django 2.1.1 on 2018-09-14 23:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0004_auto_20180914_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='river',
        ),
        migrations.AddField(
            model_name='fish',
            name='river',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='river', to='flyFishing.River'),
        ),
    ]
