# Generated by Django 2.1.1 on 2018-09-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0009_auto_20180918_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='fish',
            name='river',
            field=models.ManyToManyField(null=True, to='flyFishing.River'),
        ),
    ]
