# Generated by Django 2.1.1 on 2018-09-19 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0010_fish_river'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fish',
            name='river',
            field=models.ManyToManyField(to='flyFishing.River'),
        ),
    ]
