# Generated by Django 2.1.1 on 2018-09-21 02:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0011_auto_20180919_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='river',
        ),
        migrations.AddField(
            model_name='fish',
            name='river',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flyFishing.River'),
        ),
    ]
