# Generated by Django 2.1.1 on 2018-09-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0012_auto_20180920_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='river',
        ),
        migrations.AddField(
            model_name='fish',
            name='river',
            field=models.ManyToManyField(related_name='river', to='flyFishing.River'),
        ),
    ]
