# Generated by Django 2.1.1 on 2018-09-21 19:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0013_auto_20180921_1318'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fish',
            name='river',
        ),
        migrations.AddField(
            model_name='river',
            name='active_fish',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flyFishing.Fish'),
        ),
    ]
