# Generated by Django 2.1.1 on 2018-09-21 19:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0015_auto_20180921_1325'),
    ]

    operations = [
        migrations.CreateModel(
            name='FishPerRiver',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basePoints', models.IntegerField(null=True)),
                ('river', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flyFishing.River')),
                ('species', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='flyFishing.Fish')),
            ],
        ),
    ]
