# Generated by Django 2.1.1 on 2018-09-21 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0016_fishperriver'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='river',
            name='active_fish',
        ),
    ]
