# Generated by Django 2.1.1 on 2018-09-21 21:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0017_remove_river_active_fish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishperriver',
            name='river',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='flyFishing.River'),
        ),
    ]
