# Generated by Django 2.1.1 on 2018-09-24 22:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('flyFishing', '0018_auto_20180921_1527'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishperriver',
            name='river',
        ),
        migrations.RemoveField(
            model_name='fishperriver',
            name='species',
        ),
        migrations.AddField(
            model_name='fish',
            name='relatedRiver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fish', to='flyFishing.River'),
        ),
        migrations.DeleteModel(
            name='FishPerRiver',
        ),
    ]
